# Copyright 2025 Lawrence Livermore National Security, LLC and other
# Benchpark developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

# For testing
# FROM test-thicket

FROM ghcr.io/llnl/thicket:latest

USER root

RUN . /opt/global_py_venv/bin/activate && \
    python3 -m pip install "git+https://github.com/LLNL/treescape.git@main-2026-04-01"

USER ${NB_USER}
