# Copyright 2025 Lawrence Livermore National Security, LLC and other
# Benchpark developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

# For testing
# FROM test-thicket

FROM ghcr.io/llnl/thicket:ics-2026

USER root

RUN git clone https://github.com/LLNL/treescape ${GIT_CLONE_STAGING_DIR}/treescape && \
    cd ${GIT_CLONE_STAGING_DIR}/treescape && \
    git checkout main-2026-04-15

RUN . /opt/global_py_venv/bin/activate && \
    cd ${GIT_CLONE_STAGING_DIR}/treescape && \
    python3 -m pip install .

USER ${NB_USER}
