name: Build containers and push to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to use for the uploaded containers
      
jobs:
  build-and-upload-containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      # Only allow 1 job to run at a time to avoid dependency issues
      max-parallel: 1
      matrix:
        containers_to_build:
          - ["Dockerfile.caliper", "ghcr.io/ilumsden/hpdc-caliper"]
          - ["Dockerfile.thicket", "ghcr.io/ilumsden/hpdc-thicket"]
          - ["Dockerfile.benchpark", "ghcr.io/ilumsden/hpdc-benchpark"]
          - ["Dockerfile.spawn", "ghcr.io/ilumsden/hpdc-test-spawn"]
          - ["Dockerfile.init", "ghcr.io/ilumsden/hpdc-test-init"]
        platform: ["linux/amd64", "linux/arm64"]

    steps:
    - name: Temporary force fail job
      run: |
        echo "There's currently an issue where this Action hangs on building the Caliper image. Aborting until this is fixed."
        exit 1

    - uses: actions/checkout@v4

    - name: Remove unneeded stuff to make space for container
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false 
        swap-storage: true
            
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
            
    - name: Pull layers if they exist
      env:
        container: "${{ matrix.containers_to_build[1] }}:${{ github.event.inputs.tag }}"
      run: docker pull ${container} || echo "${container} has not yet been pushed"
          
    - name: Build container 
      env:
        dockerfile: ${{ matrix.containers_to_build[0] }}
        container: "${{ matrix.containers_to_build[1] }}:${{ github.event.inputs.tag }}"
        platform: ${{ matrix.platform }}
      run: |
        docker build --platform ${platform} -f ${dockerfile} -t ${container} .
        
    - name: Deploy container
      env:
        container: "${{ matrix.containers_to_build[1] }}:${{ github.event.inputs.tag }}"
      run: docker push ${container}